### ISSUE TITLE
Nuget package isn't recognised as a NetStandard package

### ISSUE THREAD

**Issue by robj-applied** [WilliamBZA/NServicebus.SimpleInjector#14]
Hi. When I add this package to a NetStandard 2.0 project, it throws a warning because it thinks it's a Net 4.6.1 package.

I've cloned the source and can see that the dll builds as NetStandard 2.0 so I'm not sure why this is.

Happy to investigate and do a PR but not sure if you want somebody outside of the project to do so.

Let me know, thanks.

**Comment by wleader** [comment]
I think its a one line change to fix this:

in the .nuspec file, the line:

`<file src="..\..\binaries\netstandard2.0\NServiceBus.SimpleInjector.dll" target="lib\net452" />`

should read

`<file src="..\..\binaries\netstandard2.0\NServiceBus.SimpleInjector.dll" target="lib\netstandard2.0" />`

I might try this out later, if I get time.

**Comment by robj-applied** [comment]
@wleader great, thanks

**Comment by WilliamBZA** [comment]
Thanks for the help @wleader! [3.05](https://www.nuget.org/packages/NServiceBus.SimpleInjector/3.0.5) should be netstandard now
