### ISSUE TITLE
Support Simple Injector 5.1.0

### ISSUE THREAD

**Issue by wleader** [WilliamBZA/NServicebus.SimpleInjector#18]
I have another package that I am using that requires SimpleInjector 5.1.0, but the .nuspec file in this project limits the maximum version to 5.0.3. I have been able to update to 5.1.0 and all existing tests pass. I'll be submitting a pull request soon.

**Comment by wleader** [comment]
#19 Here is a pull request that I believe will resolve my issue.

**Comment by WilliamBZA** [comment]
Thanks. I think I'll actually change the nuget range to include all of v5.*.*.

This project is less important now that NServiceBus supports the aspnet DI.

I'll release soon.

**Comment by WilliamBZA** [comment]
[Released](https://www.nuget.org/packages/NServiceBus.SimpleInjector/3.0.7)
