### ISSUE TITLE
NServicebus.SimpleInjector combined with NServicebus.SqlServerTransport does not execute installers

### ISSUE THREAD

**Issue by rubenmamo** [WilliamBZA/NServicebus.SimpleInjector#4]
I have a project which was built using the NServicebus.Bootstrap.WindowsService package.

The main method runs the following:

```
       var endpointConfiguration = new EndpointConfiguration("Service");
            endpointConfiguration.UseContainer<SimpleInjectorBuilder>(a =>
            {
                a.UseExistingContainer(ConfigureSimpleInjector());
            });

            endpointConfiguration.UseSerialization<JsonSerializer>();
            endpointConfiguration.SendFailedMessagesTo("error");
            endpointConfiguration.AuditProcessedMessagesTo("audit");
            endpointConfiguration.DefineCriticalErrorAction(OnCriticalError);
            
            var transport = endpointConfiguration.UseTransport<SqlServerTransport>();
            transport.UseSchemaForQueue(schema: "bus", queueName: "error");
            transport.UseSchemaForQueue(schema: "bus", queueName: "audit");
            transport.UseSchemaForEndpoint(schema: "bus", endpointName: "Service");
            
            var persistence = endpointConfiguration.UsePersistence<NHibernatePersistence>();

            endpointConfiguration.EnableInstallers();
            
            endpoint = await Endpoint.Start(endpointConfiguration)
                .ConfigureAwait(false);
            PerformStartupOperations(endpoint);
```
below is the definition of ConfigureSimpleInjector
```

    private Container ConfigureSimpleInjector()
    {
        var container = new Container();
        // registrations go here
        return container;
    }
```

When I run this code, the persistence tables are generated but the transport tables are not generated. If I comment out 
```
            endpointConfiguration.UseContainer<SimpleInjectorBuilder>(a =>
            {
                a.UseExistingContainer(ConfigureSimpleInjector());
            });
```
the tables are generated.

**Comment by WilliamBZA** [comment]
Thanks @rubenmamo.

It looks like this has something to do with how SimpleInjector deals with registrations of collections. When a collection is registered SimpleInjector doesn't update the list of registered types until the container is built. As a result, it looks like we're updating the collections that have been registered.

In this scenario it means that only the last registered and the first registered installer will actually sit in the container.

I'll have a release out for you shortly to try.

**Comment by rubenmamo** [comment]
Great thanks.

**Comment by WilliamBZA** [comment]
Updated package released: https://www.nuget.org/packages/NServiceBus.SimpleInjector/1.0.9

**Comment by rubenmamo** [comment]
Hi William, 
The problem was solved using the updated package, however I had some issues with getting it to build just by updating the package.

The nuget package has these dependencies:
* SimpleInjector (>= 3.2.3 && <= 3.3.2)
* SimpleInjector.Extensions.ExecutionContextScoping (>= 3.2.3 && <= 3.3.2)

however the solution would not build when I had SimpleInjector v 3.2.3 as it was giving errors saying that NServiceBus.SimpleInjector references SimpleInjector v3.3.2 whilst the one installed is v3.2.3.
I suggest you update the dependencies in the package so that other people don't have the same issue.

Whilst I was trying to solve this issue I noticed that the NserviceBus.SimpleInjector assembly is using version number 0.1.0.0 instead 1.0.9.0, is this intended?

Ruben

**Comment by rubenmamo** [comment]
The below is the exact error I got:

Severity: Error
Code: CS1705
Assembly 'NServiceBus.SimpleInjector' with identity 'NServiceBus.SimpleInjector, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' uses 'SimpleInjector, Version=3.3.2.0, Culture=neutral, PublicKeyToken=984cb50dea722e99' which has a higher version than referenced assembly 'SimpleInjector' with identity 'SimpleInjector, Version=3.2.3.0, Culture=neutral, PublicKeyToken=984cb50dea722e99'

**Comment by WilliamBZA** [comment]
Ah man, downgrading binding redirects 😞 

I'll have to release 1.0.10 with the correct bindings.

**Comment by WilliamBZA** [comment]
1.0.10 released: https://www.nuget.org/packages/NServiceBus.SimpleInjector/1.0.10

Sorry about the messup.

**Comment by rubenmamo** [comment]
No problems at all. Your speed in tackling issues more than makes up for it :)

**Comment by rubenmamo** [comment]
I can confirm it works with both the 3.2.3 and 3.3.2 versions of SimpleInjector
