### ISSUE TITLE
Is Container.Clone necessary?

### ISSUE THREAD

**Issue by charlessolar** [WilliamBZA/NServicebus.SimpleInjector#5]
I'm spiking a switch from StructureMap to SimpleInjector and using your library to connect up NSB.  After running some tests though, for every message received it constructs an entirely new container?  
Is there a way around this?

I know NSB has a `CreateChildBuilder` feature - not exactly sure what benefits it provides but the cost of spawning a new container every `CreateChildBuilder` is not cheap
<img width="1042" alt="sshot-84" src="https://cloud.githubusercontent.com/assets/1750226/25410571/43343c84-29dd-11e7-9816-5af73a98616f.png">

Perhaps there can be a way to disable cloning?

*Edit* Don't want to come off as confrontational - thanks for the work on this project!

**Comment by WilliamBZA** [comment]
Clone method removed, I'll release shortly.

Thanks for the help @volak!

**Comment by WilliamBZA** [comment]
Package release and documentation updated.
