### ISSUE TITLE
Supporting NServiceBus 7.0.1 ? 

### ISSUE THREAD

**Issue by AndyNeal** [WilliamBZA/NServicebus.SimpleInjector#7]
FWIW the updates appear pretty straightforward to bring this up to support NServiceBus 7.0.1 (current nuspec limits to 7.0.0 - I think that was the RC).  Removing IConfigurationSource (deprecated) and adding builder.UseTransport<AcceptanceTestingTransport>() in DefaultServer.cs passes tests.  

I have the updates locally (they are pretty minor) but was unable to create a pull request?

FWIW looks like SimpleInjector 4.3.0 deos have some changes around collection registration

**Comment by WilliamBZA** [comment]
Thanks @AndyNeal, you should be able to for the repo and do a PR that way?

**Comment by WilliamBZA** [comment]
Closing as the release has been made 🎉
